"""empty message

Revision ID: 0edee97fd678
Revises: 
Create Date: 2018-07-05 13:02:12.414456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edee97fd678'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_breakfast', sa.Column('breakfast_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_breakfast_post_id_fkey', 'comments_breakfast', type_='foreignkey')
    op.create_foreign_key(None, 'comments_breakfast', 'breakfast', ['breakfast_id'], ['id'])
    op.drop_column('comments_breakfast', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_breakfast', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments_breakfast', type_='foreignkey')
    op.create_foreign_key('comments_breakfast_post_id_fkey', 'comments_breakfast', 'breakfast', ['post_id'], ['id'])
    op.drop_column('comments_breakfast', 'breakfast_id')
    # ### end Alembic commands ###
