"""empty message

Revision ID: 9f622a2e314b
Revises: 0edee97fd678
Create Date: 2018-07-05 14:35:14.307571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f622a2e314b'
down_revision = '0edee97fd678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_dinner', sa.Column('dinner_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_dinner_pickup_id_fkey', 'comments_dinner', type_='foreignkey')
    op.create_foreign_key(None, 'comments_dinner', 'dinner', ['dinner_id'], ['id'])
    op.drop_column('comments_dinner', 'pickup_id')
    op.add_column('comments_lunch', sa.Column('lunch_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_lunch_product_id_fkey', 'comments_lunch', type_='foreignkey')
    op.create_foreign_key(None, 'comments_lunch', 'lunch', ['lunch_id'], ['id'])
    op.drop_column('comments_lunch', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_lunch', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments_lunch', type_='foreignkey')
    op.create_foreign_key('comments_lunch_product_id_fkey', 'comments_lunch', 'lunch', ['product_id'], ['id'])
    op.drop_column('comments_lunch', 'lunch_id')
    op.add_column('comments_dinner', sa.Column('pickup_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments_dinner', type_='foreignkey')
    op.create_foreign_key('comments_dinner_pickup_id_fkey', 'comments_dinner', 'dinner', ['pickup_id'], ['id'])
    op.drop_column('comments_dinner', 'dinner_id')
    # ### end Alembic commands ###
